name: 'Reindex'

on:
  release:
    types: [prereleased,released]

jobs:
  reindex:
    name: 'Reindex updates'
    runs-on: [self-hosted,FlipperZero]
    steps:
      - name: Trigger reindex
        uses: wei/curl@master

